version: '3'

networks:
  petshopApi:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: appserver
    ports:
      - '8088:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - petshopApi
    environment:
      UID: UID
      GID: GID

  mysql:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: petshop-api
      MYSQL_USER: nelwhix
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - petshopApi

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: app
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - petshopApi
    environment:
      UID: UID
      GID: GID

  composer:
    image: composer:latest
    container_name: pkgManager
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - petshopApi